server:
  port: 8000


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:3005
          predicates:
            - Path=/users/**

        - id: POST-SERVICE
          uri: http://localhost:3010
          predicates:
            - Path=/posts/**


        - id: COMMENT-SERVICE
          uri: http://localhost:3015
          predicates:
            - Path=//posts/{postId}/comments/**


        - id: LIKE-SERVICE
          uri: http://localhost:3020
          predicates:
            - Path=/postsOrComments/{postOrCommentId}/**

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
