server:
  port: 8000


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://172.17.0.3:3005
          predicates:
            - Path=/users/**

        - id: POST-SERVICE
          uri: http://172.17.0.3:3010
          predicates:
            - Path=/posts/**


        - id: COMMENT-SERVICE
          uri: http://172.17.0.3:3015
          predicates:
            - Path=/posts/{postId}/comments/**


        - id: LIKE-SERVICE
          uri: http://172.17.0.3:3020
          predicates:
            - Path=/postsOrComments/{postOrCommentId}/**

        - id: AUTHENTICATION-AUTHORIZATION-SERVICE
          uri: http://172.17.0.3:3000
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url:http://172.17.0.3:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
    endpoint:
      health:
        show-details: always